// Cover images and optional links. Gallery images are also referenced directly in the project HTML.
window.PORTFOLIO_ASSETS = {
  "cv": "",
  "linkedin": "",
  "jinx": "",
  "images": {
    "virtual-driving-school-cover": "assets/virtual-driving-school-cover.jpg",
    "take-that-this-life-cover": "assets/take-that-this-life-cover.jpg",
    "classified-france-44-cover": "assets/classified-france-44-cover.jpg",
    "starfall-commander-cover": "assets/starfall-commander-cover.jpg",
    "pinball-lockdown-freedom-cover": "assets/pinball-lockdown-freedom-cover.jpg",
    "virtual-driving-school-gallery-1": "assets/virtual-driving-school-new-1.jpg",
    "virtual-driving-school-gallery-2": "assets/virtual-driving-school-new-2.jpg",
    "take-that-this-life-gallery-1": "assets/take-that-this-life-puzzles.png",
    "take-that-this-life-gallery-2": "assets/take-that-this-life-matching.png",
    "classified-france-44-gallery-1": "assets/classified-france-44-loadout.jpg",
    "classified-france-44-gallery-2": "assets/classified-france-44-combat.jpg",
    "pinball-lockdown-freedom-gallery-1": "",
    "pinball-lockdown-freedom-gallery-2": "",
    "virtual-driving-school-gallery-3": "assets/virtual-driving-school-new-3.jpg",
    "virtual-driving-school-gallery-4": "assets/virtual-driving-school-new-4.jpg",
    "virtual-driving-school-gallery-5": "assets/virtual-driving-school-new-5.jpg",
    "virtual-driving-school-gallery-6": "assets/virtual-driving-school-new-6.jpg",
    "take-that-this-life-gallery-3": "assets/take-that-this-life-rewards.png",
    "take-that-this-life-gallery-4": "assets/take-that-this-life-areas.png",
    "take-that-this-life-gallery-5": "assets/take-that-this-life-daily-spin.png",
    "take-that-this-life-gallery-6": "assets/take-that-this-life-level-selection.png",
    "classified-france-44-gallery-3": "assets/classified-france-44-tactical-ui.jpg",
    "classified-france-44-gallery-4": "assets/classified-france-44-campaign-map.jpg",
    "classified-france-44-gallery-5": "assets/classified-france-44-basecamp.jpg",
    "classified-france-44-gallery-6": "assets/classified-france-44-factions.jpg",
    "virtual-driving-school-gallery-7": "assets/virtual-driving-school-new-7.jpg",
    "virtual-driving-school-gallery-8": "assets/virtual-driving-school-new-8.jpg"
  }
};
